### ISSUE TITLE
led is not working

### ISSUE THREAD

**Issue by imbmf** [shabaz123/PocketScarface#1]
Greetings,
thank you for this great project but i found that led is not working.

**Comment by shabaz123** [comment]
Hi!
Sorry, I added the LED to the circuit but didn't add the code and forgot about it.
It is easy to add. After line 41, type (with the indentation to match the code):
`boardled.value = True`
Then after the current line 45, add:
`boardled.value = False`

That area of code will look like this after you make the changes:

```
               asource.file = open(fnames[idx], "rb")
                start = time.monotonic()
                boardled.value = True
                i2s.play(asource)  # play the audio source
                while i2s.playing:
                    pass
                stop = time.monotonic()
                boardled.value = False
                print(f"Played {fnames[idx]} {stop - start} sec")

```

Then the green LED on the Pi Pico (next to the USB connector) should work. if you want to use an externally wired LED connected to GP12 (pin 16) then edit line 25, changing from:

`    boardled = digitalio.DigitalInOut(board.GP25)`

to:

`    boardled = digitalio.DigitalInOut(board.GP12)`

**Comment by imbmf** [comment]
I am using GP12 it works like charm!
Thank you very much!

**Comment by shabaz123** [comment]
Awesome! Glad it's working!
